time machine fixes 1
IFRCGo/go-api pull request #1083
Opened 2021-05-26 10:34 UTC by vdeak

2021-05-26 10:45 UTC, szabozoltan69 commented
Hi Viktor! The situation is: in develop branch the api/management/commands/triggers_to_db.py is CRLF terminated. That is why it seems to be conflicting.
In case of merging just use your new (LF terminated) file, it will work fine.

(I shall check how many CRLF terminated file exists in develop now. Should be fixed all.)

2021-05-26 10:48 UTC, szabozoltan69 commented
(Recently they are CRLF terminated:
deployments/drf_views.py
api/management/commands/triggers_to_db.py
api/views.py
api/drf_views.py
api/serializers.py

I found them via: find . -not -type d -exec file "{}" ";" | grep CRLF

2021-05-27 04:44 UTC, thenav56 requested changes

2021-05-27 04:44 UTC, thenav56 commented on api/management/commands/triggers_to_db.py
> +
Let's use the Django signal for this. (in `api/receivers.py`)

Here is a sample.
```python3
@receiver(post_save, sender=Appeal)
def add_update_appeal_history(sender, instance, created, **kwargs):
    fields_watched = [
        field.name for field in AppealHistory._meta.get_fields()
        if field.name not in ['id', 'appeal', 'valid_from', 'valid_to']
    ]
    now = timezone.now()
    latest_attributes = {
        field: getattr(instance, field)
        for field in fields_watched
    }.update(dict(
        appeal=instance,
        valid_from=now,
        # valid_to=  # Let's leave this to null and when we filter in the views.py lets coalesce this with now date
    ))

    if created:  # Appeal Insert
        AppealHistory.objects.create(**latest_attributes)
    else:  # Appeal Update
        appeal_history = AppealHistory.objects.filter().order_by('id').last()
        if appeal_history and not any([getattr(instance, field) != getattr() for field in fields_watched]):
            # Watched fields are not changed
            return
        appeal_history.valid_to = now
        appeal_history.save(update_fields='valid_to')
        # Create a new appeal history if changed
         AppealHistory.objects.create(**latest_attributes)
```

2021-05-27 04:44 UTC, thenav56 commented on api/models.py
> +        return 'APPEALHISTORY'
Is this used? If yes let's use an enum instead of a manual string.

2021-06-01 15:09 UTC, closed without merging