Add field modified_by in project model
IFRCGo/go-api pull request #1153
Opened 2021-08-10 11:43 UTC by k9845

Addresses xxxxxx 

## Changes
- Added `modified_by` field in project model

## Checklist 
Things that should succeed before merging.

- [x] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2021-08-13 05:01 UTC, thenav56 requested changes

2021-08-13 05:01 UTC, thenav56 commented on deployments/serializers.py
> +        return project
We can also do like this (with single commit)

```suggestion
        validated_data['modified_by'] = self.context['request'].user
        return super().update(instance, validated_data)
```

2021-08-16 03:50 UTC, thenav56 approved these changes

2021-08-16 03:53 UTC, thenav56 commented
@vdeak If everything is okay, could you merge and deploy to staging. cc: @batpad

2021-08-16 08:01 UTC, merged

2021-08-16 08:43 UTC, vdeak commented
@thenav56 Deployed to Stage