Feature/dref operational overview
IFRCGo/go-api pull request #1432
Opened 2022-05-18 04:01 UTC by k9845

Addresses xxxxxx 

## Changes

* Detailed list or prose of changes
* ...

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2022-06-03 04:54 UTC, thenav56 requested changes

2022-06-03 04:54 UTC, thenav56 commented on api/drf_views.py
> +from django.db.models.functions import Coalesce
Not used.

2022-06-03 04:54 UTC, thenav56 commented on api/drf_views.py
> +from deployments.models import EmergencyProject
Not used.

2022-06-03 04:54 UTC, thenav56 commented on dref/views.py
> +        dref.save(update_fields=['is_published'])
```suggestion
        if not dref.is_published:
            dref.is_published = True
            dref.save(update_fields=['is_published'])
```

2022-06-03 04:54 UTC, thenav56 commented on dref/views.py
> +        serializer = DrefSerializer(dref, partial=True, context={'request': request})
partial is not required here. It is used for update.

2022-06-03 04:54 UTC, thenav56 commented on dref/views.py
> +        serializer = DrefOperationalUpdateSerializer(operational_update, partial=True, context={'request': request})
Same as above.

2022-06-03 04:54 UTC, thenav56 commented on dref/serializers.py
> +            dref = get_object_or_404(Dref, id=dref.id)
Not required.

2022-06-03 04:54 UTC, thenav56 commented on dref/serializers.py
> +                    )
```suggestion
            dref_operational_update = DrefOperationalUpdate.objects.filter(dref=dref).order_by('-operational_update_number').first()
            if dref_operational_update and not dref_operational_update.is_published:
                raise serializers.ValidationError(
                    ugettext(
                        'Can\'t create Operational Update for not published Operational Update %s id and Operational Update Number %i.'
                        % (dref_operational_update.id, dref_operational_update.operational_update_number)
                    )
                )
```

2022-06-03 04:54 UTC, thenav56 commented on dref/serializers.py
> +        dref_operational_update = DrefOperationalUpdate.objects.filter(dref=dref)
Since we are using `dref_operational_update` here, let's fetch operational_object here instead of count and fetch.

2022-06-03 04:54 UTC, thenav56 commented on dref/serializers.py
> +        dref = validated_data.get('dref')
```suggestion
        dref = validated_data['dref']
```

2022-06-03 04:54 UTC, thenav56 commented on dref/models.py
> +    actual = models.IntegerField(verbose_name='Actual', null=True, blank=True)
```suggestion
    target = models.IntegerField(verbose_name=_('Target'), null=True, blank=True)
    actual = models.IntegerField(verbose_name=_('Actual'), null=True, blank=True)
```

2022-06-07 05:21 UTC, thenav56 approved these changes

2022-06-07 05:52 UTC, merged

2022-06-07 06:07 UTC, szabozoltan69 commented
Deployed to staging.