Fix/dref final report
IFRCGo/go-api pull request #1465
Opened 2022-06-28 02:56 UTC by k9845

Addresses xxxxxx 

## Changes

* Detailed list or prose of changes
* ...

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2022-07-08 06:14 UTC, thenav56 requested changes
Also, can we merge 5 migrations into one?

2022-07-08 06:14 UTC, thenav56 commented on dref/serializers.py
> +            raise serializers.ValidationError('Can\'t Update %s dref for publish Field Report' % self.instance.id)
ugettext

2022-09-13 11:20 UTC, frozenhelium commented
@szabozoltan69  please do the honors!

2022-09-13 11:25 UTC, merged

2022-09-13 11:26 UTC, szabozoltan69 commented
Will be deployed ASAP (in 8 minutes).

2022-09-13 11:33 UTC, szabozoltan69 commented
@frozenhelium Deployed