Add optimistic lock in dref
IFRCGo/go-api pull request #1555
Opened 2022-10-18 08:13 UTC by k9845

Addresses xxxxxx 

## Changes

* Detailed list or prose of changes
* ...

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2022-10-20 08:34 UTC, frozenhelium requested changes

2022-10-20 08:34 UTC, frozenhelium commented on dref/serializers.py
> +        modified_at = validated_data.get('modified_at')
Use pop, use None as default value

2022-10-20 08:34 UTC, frozenhelium commented on dref/serializers.py
> +            return dref
Throw error if
- modified_at is None, 'modified_at is required'
- modified_at != instance.modified_at, 'OBSOLETE_PAYLOAD'
Note: defined 'OBSOLETE_PAYLOAD' as a static value, client will use this string to identify this type of error. Please add a note in code for this as well.

2022-10-20 08:34 UTC, frozenhelium commented on dref/test_views.py
> +        self.assertEqual(response.status_code, 200)
This should be 400, also assert for the error response
Add a test case to verify `modified_at` is not null

2022-10-24 04:47 UTC, thenav56 commented on dref/models.py
> +        default=datetime.now, blank=True
Use auto_now instead of datetime.now
https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.DateField.auto_now

2022-10-24 09:56 UTC, merged