Add openapi endpoint
IFRCGo/go-api pull request #1829
Opened 2023-06-22 11:22 UTC by thenav56

Add base openapi endpoint

2023-07-03 15:25 UTC, frozenhelium requested changes

2023-07-03 15:25 UTC, frozenhelium commented on main/urls.py
> +        contact=openapi.Contact(email="admin@thedeep.io"),
Let's update these info for IFRC

2023-07-04 00:35 UTC, thenav56 commented on main/urls.py
> +        contact=openapi.Contact(email="admin@thedeep.io"),
Done

2023-07-04 05:22 UTC, tnagorra commented
## OpenAPI v3

We have updated the OpenAPI to version 3.
It includes a command to show all of the errors/warning related to schema

Here is an output of `docker-compose exec serve ./manage.py spectacular --color`

![image](https://github.com/IFRCGo/go-api/assets/4928045/390cb560-c101-48a1-ba3a-49e863bdbbc5)

## Redoc

We are now using Redoc to generate documentation for http://localhost:8000/docs/
There might be minor differences from the previous generated documentation.

## Next Steps

- Fix the errors/warning listed gradually.
- Check if the generated types are correct for all of the endpoints.

@batpad @szabozoltan69 Can we also discuss on how we can continue this work and improve the generated OpenAPI types.

2023-07-04 06:17 UTC, frozenhelium commented
@szabozoltan69 please review and merge this

2023-07-04 06:18 UTC, frozenhelium approved these changes

2023-07-04 06:20 UTC, szabozoltan69 approved these changes

2023-07-04 06:20 UTC, merged

2023-07-04 06:26 UTC, batpad commented
Spectacular work, @thenav56 @tnagorra ! Let's discuss how we can fix up errors on the dev call or so.

2023-07-04 06:42 UTC, szabozoltan69 commented
Merged to develop and deployed to Staging. (Error fixing later)

2023-07-04 06:45 UTC, szabozoltan69 commented
![kép](https://github.com/IFRCGo/go-api/assets/6050643/66e2a038-ff21-4545-b1eb-39d676a3d34d)

2023-07-04 06:51 UTC, szabozoltan69 commented
@thenav56 @tnagorra is it possible to use this /docs endpoint interactively? So, giving some arguments and sending the request?

2023-07-04 07:13 UTC, szabozoltan69 commented
Or maybe could we keep the old possibility as a /docs_v1 ?

2023-07-04 08:49 UTC, thenav56 commented
@szabozoltan69 swagger-ui has interaction, maybe we can use that http://localhost:8000/api-docs/swagger-ui/

2023-07-04 08:53 UTC, tnagorra commented
@szabozoltan69 I also suggest we use https://goadmin-stage.ifrc.org/api-docs/swagger-ui/ for interactivity.

2023-07-04 13:47 UTC, szabozoltan69 commented
I am not sure that this kind of output structure could remain, which is in https://goadmin-stage.ifrc.org/api/v2/brief
It's just a healthcheck endpoint, for human reading, not for any other machine usage.
(It's the only one which is "hacked" like this.)

2023-07-04 14:27 UTC, thenav56 commented
I think that should be okay. Basically, we define a serializer that we use to generate the data instead of a manual response. Then the schema will show the structure.