Add serializer for registration view
IFRCGo/go-api pull request #1841
Opened 2023-07-05 10:12 UTC by k9845

Addresses xxxxxx 

## Changes

* Detailed list or prose of changes
* ...

## Checklist 
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2023-07-06 05:08 UTC, thenav56 requested changes

2023-07-06 05:08 UTC, thenav56 commented on registrations/serializers.py
> +            User.objects.filter(username=username).delete()
Not required, this should be handled by transaction

2023-07-06 05:08 UTC, thenav56 commented on registrations/serializers.py
> +        pending.save()
```suggestion
        pending = Pending(
            user=user,
            justification=justification,
            token=get_random_string(length=32)
        )
        if not is_staff:
            pending.admin_token_1 = get_random_string(length=32)
        pending.save()
```

2023-07-06 05:08 UTC, thenav56 commented on registrations/test_views.py
> +        resp = self.client.post('/register', data=body, format='json')
Maybe this works
```suggestion
        resp = self.client.post('/register', json=body)
```

2023-07-06 05:08 UTC, thenav56 commented on registrations/test_views.py
> +        country = Country.objects.get(name='country')
Please confirm this.

2023-07-06 05:08 UTC, thenav56 commented on registrations/test_views.py
> +        self.assertEqual(resp.status_code, 400)
Let's assert for user count as well and error response.

2023-07-06 05:08 UTC, thenav56 commented on registrations/utils.py
> +def is_valid_domain(email):
Add a note to update the function definition.

2023-07-06 05:09 UTC, thenav56 requested changes

2023-07-06 05:09 UTC, thenav56 commented on registrations/serializers.py
> +    country = serializers.IntegerField()
Let's define max_length here as well.

2023-07-13 03:55 UTC, k9845 commented
Closing in favour of `https://github.com/IFRCGo/go-api/pull/1846`

2023-07-13 03:56 UTC, k9845 commented
Closing in favour of `https://github.com/IFRCGo/go-api/pull/1846`

2023-07-13 03:56 UTC, closed without merging