Add sample token with private and public key
IFRCGo/go-api pull request #2026
Opened 2024-01-29 11:06 UTC by susilnem

Addresses 
 - https://github.com/IFRCGo/go-api/issues/1982

## Changes
- Create a Model for ExternalToken Generation

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-04-25 04:51 UTC, thenav56 requested changes

2024-04-25 04:51 UTC, thenav56 commented on registrations/models.py
> +    token = models.TextField(verbose_name=_('token'), editable=False)
We only store jti instead of whole token

2024-04-25 04:51 UTC, thenav56 commented on registrations/models.py
> +    is_disabled = models.BooleanField(verbose_name=_('is disabled?'), default=False)
For now, let's comment it out and add a note, as we haven't implemented blacklist in this phase.

2024-04-25 04:51 UTC, thenav56 commented on registrations/models.py
> +        return f'{self.user.username} ({self.created_at.strftime("%Y-%m-%d")})'
```suggestion
        return f'{self.user_id} ({self.created_at.strftime("%Y-%m-%d")})'
```

2024-04-25 04:51 UTC, thenav56 commented on registrations/serializers.py
> +        return data
Let's add a max limit as well

```suggestion
    def validate_expire_timestamp(self, date):
        if date < timezone.now():
            raise serializers.ValidationError('Expire timestamp must be in the future.')
        return date
```

2024-04-25 04:51 UTC, thenav56 commented on registrations/serializers.py
> +            validated_data['expire_timestamp'] = timezone.now() + timedelta(days=7)
Default will be a bit more than that. We need to discuss this.

2024-04-25 04:51 UTC, thenav56 commented on registrations/serializers.py
> +            raise serializers.ValidationError('Please Provide private and public key.')
```suggestion
            raise serializers.ValidationError('Please contact system adminstrators to configurate private and public key.')
```

2024-04-25 04:51 UTC, thenav56 commented on registrations/serializers.py
> +        validated_data['token'] = jwt_encode_handler(payload)
We don't store the token to the database, we only need to send it back when creating a new token.
NOTE: We store jit instead

2024-04-25 04:51 UTC, thenav56 commented on registrations/utils.py
> +        algorithm='RS256',
We are using `ES256`

2024-04-25 04:51 UTC, thenav56 commented on registrations/views.py
> +    queryset = UserExternalToken.objects.exclude(is_disabled=True)
We can show all the user tokens

```suggestion
    queryset = UserExternalToken.objects.exclude(is_disabled=True)
```

2024-04-25 04:51 UTC, thenav56 commented on registrations/views.py
> +        )
We don't need to delete, instead just disable. Which will be used when we implement blacklisting.

2024-04-25 04:51 UTC, thenav56 commented on registrations/models.py
> +
Let's add a title

2024-04-26 09:00 UTC, thenav56 commented on api/drf_views.py
> +        user = self.get_object()
```suggestion
        user = request.user
```

2024-04-26 09:00 UTC, thenav56 commented on main/settings.py
> +    #jwt private and public key
```suggestion
    # jwt private and public key
```

2024-04-26 09:00 UTC, thenav56 commented on registrations/models.py
> +    )
Let's use uuid field instead of charfield

2024-04-26 09:00 UTC, thenav56 commented on registrations/serializers.py
> +        validated_data['jti'] = get_random_string(length=32)
Let's use uuid4

2024-04-26 09:00 UTC, thenav56 commented on registrations/serializers.py
> +            raise serializers.ValidationError('User must accept Montandon license terms.')
For now we skip this..  so let's comment it out.

2024-04-26 09:00 UTC, thenav56 commented on registrations/serializers.py
> +        }
Let's move this section to model

2024-04-26 09:00 UTC, thenav56 commented on registrations/serializers.py
> +        UserExternalToken.objects.create(**validated_data)
```suggestion
        instance = super().create(validated_data)
```

2024-04-26 09:00 UTC, thenav56 commented on registrations/models.py
> +        return f'{self.user.username} ({self.created_at.strftime("%Y-%m-%d")})'
Let's add an expiry information there as well.

2024-04-26 09:03 UTC, thenav56 requested changes

2024-04-26 09:03 UTC, thenav56 commented on registrations/serializers.py
> +            raise serializers.ValidationError('Expire timestamp must be less than 1 year.')
```suggestion
            raise serializers.ValidationError('Expire timestamp must be less than {settings.____} days.')
```

2024-04-29 12:14 UTC, thenav56 requested changes
Last minor change

2024-04-29 12:14 UTC, thenav56 commented on registrations/test_views.py
> +            response = self.client.post('/api/v2/external-token/', data, format='json')
Let's also check if response have the newly generated token and another basic GET check as well.

2024-05-02 06:19 UTC, k9845 requested changes

2024-05-02 06:19 UTC, k9845 commented on api/drf_views.py
> +        return Response(self.get_serializer_class()(user).data)
@susilnem Let's also define the schema type

2024-05-02 06:19 UTC, k9845 commented on registrations/models.py
> +    expire_timestamp = models.DateTimeField(verbose_name=_('expire timestamp'), null=True, blank=True)
Remove null and blank.

2024-05-02 06:19 UTC, k9845 commented on registrations/models.py
> +            'userId': self.user.id,
```suggestion
            'userId': self.user_id,
```

2024-05-02 06:19 UTC, k9845 commented on registrations/serializers.py
> +    class Meta:
```suggestion
    expire_timestamp = serializers.DateTimeField(required=False)

    class Meta:
```

2024-05-02 06:19 UTC, k9845 commented on registrations/test_views.py
> +from main.test_case import APITestCase as Apitestcase
```suggestion
from main.test_case import APITestCase as GoAPITestCase
```

2024-05-02 06:19 UTC, k9845 commented on registrations/views.py
> +from registrations.serializers import UserExternalTokenSerializer
Move this before models import

2024-05-03 08:41 UTC, frozenhelium commented
@susilnem Let's also capture `created_at` and also add it to the `GET` endpoint.
CC: @thenav56

2024-05-03 09:53 UTC, frozenhelium commented
Hi @szabozoltan69, could you please merge and deploy it to staging. 

## Before you merge!
Please note that it requires new env variables. You can generate the values for the token using the bash script

```bash
#!/usr/bin/env bash

mkdir -p keys/

function gen_key {
    # EdDSA
    # openssl genpkey -algorithm ed25519 -out keys/$1
    # openssl pkey -in keys/$1 -pubout > keys/$1.pub

    # ES256
    openssl ecparam -name prime256v1 -genkey -noout -out keys/$1
    openssl ec -in keys/$1 -pubout > keys/$1.pub
}

# Used
gen_key jwtkey-01
```

2024-05-03 09:55 UTC, frozenhelium approved these changes

2024-05-03 09:56 UTC, k9845 approved these changes

2024-05-03 12:25 UTC, merged