Add status field in alert
IFRCGo/go-api pull request #2040
Opened 2024-02-09 10:21 UTC by susilnem

Addresses
https://github.com/IFRCGo/go-api/issues/2036

## Changes

* Detailed list or prose of changes
* ...

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-02-12 08:24 UTC, k9845 approved these changes
lets add test case as well

2024-02-12 08:49 UTC, k9845 reviewed
@susilnem Lets also add test case for this

2024-02-13 05:54 UTC, thenav56 requested changes
Looks good. Few comments

2024-02-13 05:54 UTC, thenav56 commented on notifications/models.py
> +class SurgeAlertStatus(models.IntegerChoices):
Let's add a note, explaining the ordering usage here

2024-02-13 05:54 UTC, thenav56 commented on notifications/tests.py
> +        time.sleep(10)
Hmm... let's not do this… Let's mock the date time if needed.

2024-02-13 05:54 UTC, thenav56 commented on notifications/management/commands/update_alert_status.py
> +            logger.error('Error while updating alerts status: %s' % str(e))
Let's use exc_info=True
```suggestion
            logger.error('Error while updating alerts status', exc_info=True)
```

2024-02-13 05:54 UTC, thenav56 commented on notifications/management/commands/update_alert_status.py
Let's not use generic names for stuffs which are defined as global

Maybe `update_surge_alert_status`

2024-02-13 05:54 UTC, thenav56 commented on notifications/models.py
> +    status = models.IntegerField(choices=SurgeAlertStatus.choices, verbose_name=_('alert status'), default=0)
```suggestion
    status = models.IntegerField(choices=SurgeAlertStatus.choices, verbose_name=_('alert status'), default=SurgeAlertStatus.OPEN)
```

2024-02-13 10:25 UTC, thenav56 approved these changes

2024-02-13 10:34 UTC, thenav56 commented
Hey @szabozoltan69, could you review and merge/deploy this to staging?

2024-02-13 10:39 UTC, merged

2024-02-13 10:51 UTC, thenav56 commented
Hey @szabozoltan69 

We also need to run this after deployment to initiate the status. After that, it will be updated every 12 hours.


./manage.py update_surge_alert_status

2024-02-13 10:57 UTC, szabozoltan69 commented
Hey @thenav56 
Deployment was ok, also the migration:
Running migrations:
  Applying notifications.0014_surgealert_status... OK
Also this was run flawless:
./manage.py update_surge_alert_status

2024-05-15 06:12 UTC, k9845 commented
@szabozoltan69 Can you run `./manage.py update_surge_alert_status` command on production? I think we missed this.

2024-05-15 07:01 UTC, szabozoltan69 commented
Now I did it.