Add Additional fields in CountrykeyDocuments
IFRCGo/go-api pull request #2117
Opened 2024-04-23 07:55 UTC by susilnem

Addresses 
- https://github.com/IFRCGo/go-api/issues/2111

## Changes
- Add fields for the CountryKeyDocuments
- Update the ingest_ns_document script

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-04-25 11:37 UTC, samshara requested changes
Currently the ordering doesn't work as expected when `year` is `null` or `end_year` is `null`.

For example: https://country-page-ifrc.dev.datafriendlyspace.org/api/v2/country-document/?country=20&document_type=Our+Strategic+Plan&ordering=-end_year

2024-04-25 12:00 UTC, thenav56 commented
For nulls_last.
https://docs.djangoproject.com/en/5.0/ref/models/expressions/#using-f-to-sort-null-values
https://github.com/encode/django-rest-framework/blob/master/rest_framework/filters.py#L232-L248
https://stackoverflow.com/a/75769498/3436502

2024-04-26 06:05 UTC, samshara approved these changes

2024-04-26 06:14 UTC, k9845 approved these changes

2024-04-26 06:53 UTC, merged