Fix NS directory and Capacity Issue
IFRCGo/go-api pull request #2214
Opened 2024-07-12 06:48 UTC by susilnem

Addresses:
- Data repetition for `NS capacity`
- NS Directory is Showing `None` 

## Changes
- Add unique together for NS capacity
- Delete NS Directory
- Add new migrations

>Note: Need to run the following commands manually:
```
- ./manage.py ingest_ns_capacity
- ./manage.py ingest_ns_directory
```

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-07-12 07:17 UTC, thenav56 requested changes

2024-07-12 07:17 UTC, thenav56 commented on api/management/commands/ingest_ns_capacity.py
> +            country_capacity_ids.append(country_capacity_ocac.pk)
We need to update non-unique fields as well

2024-07-12 07:17 UTC, thenav56 commented on api/management/commands/ingest_ns_capacity.py
> +                country_capacity_ids.append(country_capacity_boca.pk)
We need to update non-unique fields as well

2024-07-12 07:17 UTC, thenav56 commented on api/models.py
> +        unique_together = ("country", "assessment_code", "year")
Missing `assessment_type`

Also, looking at the source data,
assessment_code = 
 - For ocacpublic: NS_ID+Year
 - For bocapublic: NS_ID+Branch_Name+Year
 Where assessment_code already includes country and year.
 
 Maybe should use ("assessment_code", "assessment_type") as unique?

2024-07-12 07:17 UTC, thenav56 commented on api/management/commands/ingest_ns_directory.py
> -                        position__iexact=data["position"],
Any reason for this change?

I think caseinsentive search makes sense, Maybe we should update if it is changed instead of creating new?

2024-07-12 09:29 UTC, thenav56 approved these changes
@szabozoltan69 When you have time, could you review and merge this?

NOTE: We need to run this command after deployment
```bash
./manage.py ingest_ns_capacity
./manage.py ingest_ns_directory
```

2024-07-15 09:00 UTC, merged

2024-07-15 09:39 UTC, szabozoltan69 commented
Deployed to Staging.
The ingest_ns_capacity had some 
```
  warnings.warn(
/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning: DateTimeField CountryCapacityStrengthening.submission_date received a naive datetime (2019-01-20 00:00:00) while time zone support is active.
```
warnings, but run fine.
ingest_ns_directory also run fine, giving: "1647 Ns Directory added".

2024-07-15 09:39 UTC, szabozoltan69 commented
@thenav56 ^ commands were run.