FDRS: Fetch only the latest year related data
IFRCGo/go-api pull request #2280
Opened 2024-10-03 07:32 UTC by susilnem

Addresses
- https://github.com/IFRCGo/go-web-app/issues/1396

## Changes
-  `KPI_noLocalUnits` changed to `KPI_noBranches`
- Updated the cron job FDRS link
This pull request to `databank/management/commands/sources/FDRS.py`.

Improvements to data fetching and processing:

- Changed the key from `KPI_noLocalUnits` to `KPI_noBranches`.

- Updated the `prefetch` function to fetch the latest data for each indicator by using the `max` function to get the entry with the highest year. (`databank/management/commands/sources/FDRS.py`)
-  Modified the `load` function to ensure only the latest year's data is used by checking the year before setting the value. (`databank/management/commands/sources/FDRS.py`) 

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-10-03 08:02 UTC, szabozoltan69 approved these changes

2024-10-07 11:08 UTC, thenav56 requested changes

2024-10-07 11:08 UTC, thenav56 commented on databank/management/commands/sources/FDRS.py
> +            setattr(overview, field.field.name, value)
We will also need to clear the field's value if it doesn't exist in the remote source for the max year.

2024-10-07 11:08 UTC, thenav56 commented on databank/management/commands/sources/FDRS.py
> +    ("KPI_noBranches", CO.branches),
> Issue comment: https://github.com/IFRCGo/go-web-app/issues/1396#issuecomment-2388892005
> So, it has been just updated (KPI_noBranches) in the Data2 FDRS API (note that we only started collecting this information for 2023)

This needs to fetch from different endpoint?

Maybe this? https://data-api.ifrc.org/api/data2?apiKey=XX-YY-ZZ&KPI_Don_Code=DAF001&indicator=KPI_noBranches

2024-10-07 11:59 UTC, thenav56 commented on databank/management/commands/sources/FDRS.py
> +    ("KPI_noBranches", CO.branches),
This is already fixed.

2024-10-08 04:02 UTC, thenav56 approved these changes
Let's wait until approval from QA

2024-10-24 08:06 UTC, Rup-Narayan-Rajbanshi approved these changes

2024-10-24 08:09 UTC, szabozoltan69 approved these changes

2024-11-04 09:54 UTC, szabozoltan69 commented
Should we merge this?

2024-11-05 12:12 UTC, merged

2024-11-05 15:25 UTC, susilnem commented
@szabozoltan69 
we also need to run these commands:
`python manage.py ingest_databank` and `python manage.py ingest_worldbank`

2024-11-05 15:46 UTC, szabozoltan69 commented
Both were run fine (ingest_databank had a slight issue).