Add Argo hooks Implementation
IFRCGo/go-api pull request #2320
Opened 2024-11-22 06:51 UTC by susilnem

Addresses
- https://github.com/IFRCGo/go-api/issues/2310

## Changes
- Add meta annotation for the celery.
- Add post sync argo hooks:
  - [x] migrations
  - [x] Collect static
  - [ ] Alpha users

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-12-03 11:03 UTC, szabozoltan69 approved these changes

2024-12-10 10:05 UTC, thenav56 requested changes

2024-12-10 10:17 UTC, thenav56 commented
Let's test this using tc-local talos... then we can merge this

2024-12-12 05:30 UTC, susilnem commented
Hi @szabozoltan69 @Lusengeri,  
Could you please review this and merge if everything looks good?  
Thanks!

2024-12-12 08:34 UTC, Lusengeri reviewed
At the moment, the go-api isn't being managed using argocd. As such, the included argo hooks will not have any effect. I would suggest we try this out on sandbox environment. Also, using argoCD would mean replacing the current deploy pipeline. We should test this out properly before replacing the current helm-release based deployment. I am available to support this change but we would need to coordinate.

2024-12-12 08:47 UTC, thenav56 commented
> @susilnem , at the moment, the go-api isn't being managed using argocd. As such, the included argo hooks will not have any effect. I would suggest we try this out on sandbox environment first. Also, using argoCD would mean replacing the current deploy pipeline. We should test this out properly before replacing the current helm-release based deployment. I am available to support this change but we would need to coordinate.

Thanks @Lusengeri for the review!

We’re using argo-hooks for all alpha instances internally, which is a good starting point for testing and future ArgoCD integration in the go-api. It’s a good time to review and experiment with it. If you have any quick feedback on the implementation, please share!

@szabozoltan69 If you're interested, @susilnem can share a quick preview during the next dev call 😃

2025-02-07 11:18 UTC, thenav56 commented
We have disabled the argo-hooks by default... it shouldn't impact the current deployment pipeline.

2025-02-07 11:18 UTC, merged