Feature/add api for depricate
IFRCGo/go-api pull request #2340
Opened 2024-12-10 09:50 UTC by Rup-Narayan-Rajbanshi

Addresses
  - https://github.com/IFRCGo/go-api/issues/2338

## Changes
  - Add api for depricate local unit and revert depricate.

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-12-10 09:53 UTC, szabozoltan69 reviewed
Please replace the string "epricate" to "eprecate" where it occurs in the files. :-)

2024-12-10 10:35 UTC, susilnem requested changes
Minor changes

2024-12-10 10:35 UTC, susilnem commented on local_units/views.py
> +    @action(detail=True, methods=["put"], url_path="deprecate")
```suggestion
    @action(detail=True, methods=["post"], url_path="deprecate")
```

2024-12-10 10:35 UTC, susilnem commented on local_units/views.py
> +    @action(detail=True, methods=["put"], url_path="revert-deprecate")
```suggestion
    @action(detail=True, methods=["post"], url_path="revert-deprecate")
```

2024-12-10 10:35 UTC, susilnem commented on local_units/views.py
> +                {"message": f"Object {instance.id}-{instance.is_deprecated} deprecated successfully."},
```suggestion
                {"message": f"Object {instance.id} is deprecated successfully."},
```

2024-12-10 10:35 UTC, susilnem commented on local_units/views.py
> +        return response.Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
```suggestion
        serializer.is_valid(raise_exception=True)
        return response.Response(serializer.data, status=status.HTTP_200_OK)
```

2024-12-11 04:17 UTC, susilnem approved these changes
LGTM!

2024-12-11 04:36 UTC, thenav56 requested changes

2024-12-11 04:36 UTC, thenav56 commented on local_units/serializers.py
> +class LocalUnitDeprecateSerializer(serializers.Serializer):
Let's use ModelSerializer with fields mentioned below

2024-12-11 04:36 UTC, thenav56 commented on local_units/views.py
> +        """Deprecate local unit object object"""
Error if already deprecate

2024-12-11 08:57 UTC, susilnem requested changes

2024-12-11 08:57 UTC, susilnem commented on local_units/serializers.py
> +            raise serializers.ValidationError("This object is already deprecated.")
Confirm error message with FE

2024-12-11 08:57 UTC, susilnem commented on local_units/serializers.py
> +            raise serializers.ValidationError("A reason must be provided when deprecating an object.")
If required, just use serializer field

2024-12-11 08:57 UTC, susilnem commented on local_units/serializers.py
> +        return attrs
raise validation error for create method.

2024-12-11 08:57 UTC, susilnem commented on local_units/serializers.py
> +        instance.save()
use update fields

2024-12-11 08:58 UTC, susilnem requested changes
Minor changes

2024-12-12 09:17 UTC, merged