Add logic to migrate fieldreport number
IFRCGo/go-api pull request #2349
Opened 2024-12-19 03:27 UTC by sudip-khanal

Addresses 

[Migration of Field Report Data for Dynamic Title Suffixes](https://github.com/IFRCGo/go-api/issues/2332#issue-2719519411)
## Changes

* Add logic to migrate field report number from the old summary

## Checklist
Things that should succeed before merging.

- [ ] Updated/ran unit tests
- [ ] Updated CHANGELOG.md

## Release

If there is a version update, make sure to tag the repository with the latest version.

2024-12-30 07:22 UTC, susilnem requested changes
let's change the file name to `migrate_field_report_number`

2024-12-30 07:22 UTC, susilnem commented on api/management/commands/field-report-fix-suffixes.py
> +                )
Lets add a logger here.

2024-12-30 11:18 UTC, susilnem requested changes
Few changes

2024-12-30 11:18 UTC, susilnem commented on api/management/commands/migrate_field_report_number.py
> +                    id=highest_report.id
```suggestion
                  FieldReport.objects.filter(event_id=event_id, countries=country_id).exclude(
                    id=highest_report.id).update(fr_num=None)
```

2024-12-31 05:31 UTC, thenav56 requested changes

2024-12-31 05:31 UTC, thenav56 commented on api/management/commands/migrate_field_report_number.py
> +                )
Do we need this? We shouldn't mutate existing data if not required.

2024-12-31 05:31 UTC, thenav56 commented on api/management/commands/migrate_field_report_number.py
> +                    highest_report.save(update_fields=["fr_num"])
Let's use bulk manager
https://github.com/IFRCGo/go-api/blob/develop/main/managers.py#L69

2024-12-31 05:31 UTC, thenav56 commented on api/management/commands/migrate_field_report_number.py
> +            group_data = event_country_data[key]
```suggestion
            group_data = event_country_data[key] = event_country_data.get(key, {
                "highest_fr_num": 0,
                "report_highest_fr": None,
            })
```

2024-12-31 05:31 UTC, thenav56 commented on api/management/commands/migrate_field_report_number.py
> +        reports = FieldReport.objects.filter(summary__icontains="#", event__isnull=False, countries__isnull=False)
Let's exclude any event/country field reports with fr_num field with value.

Something like this
```python
# Only process event/country where we don't have fr_num defined
event_country_filter_qs = Report.objects.order_by().values('event', 'countries').annoate(
    count=models.Count('id', filter=models.Q(fr_num__isnull=True))
).exclude(count__gte=1)

report_to_process_qs = Report.objects.filter(
    # Still slow but better then doing this within python
    event__in=event_country_filter_qs.values('event'),
    countries__in=event_country_filter_qs.values('countries'),
).distinct()
```

2024-12-31 05:31 UTC, thenav56 commented on api/management/commands/migrate_field_report_number.py
> +class Command(BaseCommand):
Let's also monitor memory usages... or use iterator during for loop

2025-01-15 08:58 UTC, thenav56 approved these changes

2025-01-15 10:28 UTC, merged