ISO codes should be uppercase
IFRCGo/go-api pull request #956
Opened 2020-12-08 13:19 UTC by geohacker

ISO codes should be uppercase in the database. Fixes https://github.com/IFRCGo/go-frontend/issues/1681
This will require some frontend fixes.

@batpad @GregoryHorvath I've not been able to test this just yet as my db is locally broken because of out of order migrations.

2020-12-08 13:23 UTC, GregoryHorvath approved these changes

2020-12-08 13:25 UTC, GregoryHorvath requested changes
Country doesn't seem to have an `iso2` but an `iso3` at least on my side. Other than this it looks good.

2020-12-10 07:21 UTC, batpad commented
@geohacker this looks good to me.

Could we add the `blank=True` to the `iso` and `iso3` fields as part of this PR as well, to make them non-required in the admin?

2020-12-10 09:09 UTC, GregoryHorvath approved these changes

2020-12-10 09:19 UTC, merged